name: Check Markdown links

# Run action on pull request event
on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    # checkout to latest commit
    - uses: actions/checkout@master

    - name: Waiting for Netlify Preview
      uses: kamranayub/wait-for-netlify-action@v2.1.1
      id: netlify-preview
      with:
        site_name: "toha-guides"
        max_timeout: 60
      env:
        NETLIFY_TOKEN: ${{secrets.NETLIFY_TOKEN}}

    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v1.5.4
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        args: "--verbose ${{steps.netlify-preview.outputs.url}}"
        debug: true
        fail: true

    - name: Comment Broken Links
      uses: marocchino/sticky-pull-request-comment@v2
      if: env.lychee_exit_code != 0
      with:
        path: ./lychee/out.md
