name: Percy.io Visual Diff

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # install hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.75.1'
          # extended: true

      # build the site
      - name: Build
        run: hugo --minify

      # run percy test
      - name: Percy Test
        uses: percy/snapshot-action@v0.1.0
        with:
          build-directory: "public"
          flags: --snapshot-files=index.html,404.html,posts/,posts/writing-posts/markdown-syntax-guide/
          config: ./.github/percy-config.yml
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
